integrations:
  node_exporter:
    enabled: true
  prometheus_remote_write:
    - basic_auth:
        password: ${GRAFANA_API_KEY}
        username: 285788
      url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
loki:
  configs:
    - clients:
        - basic_auth:
            password: ${GRAFANA_API_KEY}
            username: 141865
          url: https://logs-prod-us-central1.grafana.net/api/prom/push
      name: integrations
      positions:
        filename: /tmp/positions.yaml
      target_config:
        sync_period: 10s
prometheus:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: ${GRAFANA_API_KEY}
            username: 285788
          url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345
