baseURL = "https://pickard.cc"
languageCode = "en-us"
title = "pickard.cc"
theme = "smol"
pygmentsUseClasses = true
pygmentsCodeFences = true
#pygmentsStyle = "monokai"
PygmentsCodeFences = true
#PygmentsStyle = "trac"
# Parameters
[params]
subtitle = "chris pickard's site on the world wide web"
dateFmt = "01.02.2006 15:04"

# Header
[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

# Footer
[[menu.footer]]
name = "github"
url = "https://github.com/chrispickard"
weight = 1

[[menu.footer]]
name = "twitter"
url = "https://twitter.com/chrispickard9"
weight = 2
