baseURL = "https://pickard.cc"
languageCode = "en-us"
title = "chris pickard's weblog"
theme = "smol"
pygmentsUseClasses = true
pygmentsCodeFences = true
#pygmentsStyle = "monokai"
PygmentsCodeFences = true
#PygmentsStyle = "trac"
# Parameters
[params]
subtitle = "chris pickard's weblog"
dateFmt = "01.02.2006"

# Footer
[[menu.footer]]
name = "github"
url = "https://github.com/chrispickard"
weight = 1

[[menu.footer]]
name = "twitter"
url = "https://twitter.com/chrispickard9"
weight = 2
