#!/usr/bin/env bash
set -e
set -u
set -o pipefail

ssh pickard.cc echo hello

mkdir -p ~/.config/nix/
echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
nix run github:serokell/deploy-rs
